/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.Logica;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lucas
 */
public class Minsa extends javax.swing.JFrame {

    /**
     * Creates new form GaySiElQueLoLea
     */
    public Minsa() {
        initComponents();
        this.setLocationRelativeTo(null);
        ladoD01.setSize(540, 810);
        ladoD01.setLocation(0, 0);
        content02.removeAll();
        content02.add(ladoD01, BorderLayout.CENTER);
        content02.revalidate();
        content02.repaint();
        ladoI01.setSize(540, 810);
        ladoI01.setLocation(0, 0);
        content01.removeAll();
        content01.add(ladoI01, BorderLayout.CENTER);
        content01.revalidate();
        content01.repaint();
    }
    boolean Verificacion = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ladoD01 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNacimiento = new javax.swing.JTextField();
        lblEmision = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtEmision = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        ladoI01 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jpQr = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        ladoD02 = new javax.swing.JPanel();
        jpText = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jpCarne1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jpCarne2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ladoI02 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jsText1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jsText2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel28 = new javax.swing.JLabel();
        CarnetCovid = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jpCarnet = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        lblNumeroDosis = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        Check2 = new javax.swing.JCheckBox();
        Check1 = new javax.swing.JCheckBox();
        Check4 = new javax.swing.JCheckBox();
        Check3 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        content02 = new javax.swing.JPanel();
        content01 = new javax.swing.JPanel();

        ladoD01.setBackground(new java.awt.Color(255, 255, 255));
        ladoD01.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Identifica para ingresar");
        ladoD01.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 18, 322, -1));

        cbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI - Documento Nacional de Identidad", "CE - Carnét de extranjeria", "Pasaporte", "Documento de Identidad Extranjero", "Código Temporal de Acceso", "Permiso Temporal de Permanencia" }));
        cbTipoDocumento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoDocumentoItemStateChanged(evt);
            }
        });
        cbTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoDocumentoActionPerformed(evt);
            }
        });
        ladoD01.add(cbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 94, 333, 45));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Número de Documento");
        ladoD01.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 163, -1, -1));

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });
        ladoD01.add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 185, 333, 45));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Fecha de Nacimiento");
        ladoD01.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 254, -1, -1));

        txtNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacimientoKeyTyped(evt);
            }
        });
        ladoD01.add(txtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 276, 333, 45));

        lblEmision.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEmision.setText("Fecha de Emision de tu DNI");
        ladoD01.add(lblEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 339, -1, -1));

        jCheckBox1.setText("Mantener mi sesión iniciada por 07 dias.");
        ladoD01.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 418, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel6.setText("Revisa la Politica de Privacidad de Terminos y ");
        ladoD01.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        btnContinuar.setBackground(new java.awt.Color(255, 102, 102));
        btnContinuar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnContinuarMouseClicked(evt);
            }
        });
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        ladoD01.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 333, 49));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Selecciona tu tipo de Documento");
        ladoD01.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 68, -1, -1));

        txtEmision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmisionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmisionKeyTyped(evt);
            }
        });
        ladoD01.add(txtEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 361, 333, 45));

        jLabel26.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel26.setText("Condiciones de la Plataforma");
        ladoD01.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 279, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Te damos la bienvenida a Carné de Vacunación");

        jLabel10.setText("En esta plataforma podrás:");

        jLabel11.setText("Ver y descargar tu Carné de Vacunación.");

        jLabel12.setText("Verificar la validez de un código QR.");

        jLabel13.setText("Ver el detalle de tu esquema de vacunación.");

        jLabel14.setText("Descargar tu certificado de vacunación.");

        jLabel15.setText("Solicitar el registro de tu vacunación COVID-19.");

        jpQr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Verifica un");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setText("Código QR");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/qr.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpQrLayout = new javax.swing.GroupLayout(jpQr);
        jpQr.setLayout(jpQrLayout);
        jpQrLayout.setHorizontalGroup(
            jpQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpQrLayout.setVerticalGroup(
            jpQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpQrLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpQrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpQrLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addGap(12, 12, 12)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ladoI01Layout = new javax.swing.GroupLayout(ladoI01);
        ladoI01.setLayout(ladoI01Layout);
        ladoI01Layout.setHorizontalGroup(
            ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI01Layout.createSequentialGroup()
                .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpQr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ladoI01Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel10)))))
                    .addGroup(ladoI01Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        ladoI01Layout.setVerticalGroup(
            ladoI01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI01Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addComponent(jLabel10)
                .addGap(54, 54, 54)
                .addComponent(jLabel11)
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(44, 44, 44)
                .addComponent(jpQr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        ladoD02.setBackground(new java.awt.Color(255, 255, 255));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Ingresa al Carné de Vacunacion de ");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("menores de edad");

        jLabel18.setText("Debes ser progenitor o apoderado del menor");

        jLabel19.setText("para realizar esta consulta.");

        javax.swing.GroupLayout jpTextLayout = new javax.swing.GroupLayout(jpText);
        jpText.setLayout(jpTextLayout);
        jpTextLayout.setHorizontalGroup(
            jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTextLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpTextLayout.createSequentialGroup()
                        .addGroup(jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpTextLayout.setVerticalGroup(
            jpTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTextLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jButton4.setText("Carné de Vacunación COVID-19");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono-movil (1) (2).png"))); // NOI18N

        javax.swing.GroupLayout jpCarne1Layout = new javax.swing.GroupLayout(jpCarne1);
        jpCarne1.setLayout(jpCarne1Layout);
        jpCarne1Layout.setHorizontalGroup(
            jpCarne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCarne1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jpCarne1Layout.setVerticalGroup(
            jpCarne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarne1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpCarne1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton3.setText("Carné de Vacunacion General");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefono-movil (1) (2).png"))); // NOI18N

        javax.swing.GroupLayout jpCarne2Layout = new javax.swing.GroupLayout(jpCarne2);
        jpCarne2.setLayout(jpCarne2Layout);
        jpCarne2Layout.setHorizontalGroup(
            jpCarne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCarne2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jpCarne2Layout.setVerticalGroup(
            jpCarne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarne2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpCarne2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ladoD02Layout = new javax.swing.GroupLayout(ladoD02);
        ladoD02.setLayout(ladoD02Layout);
        ladoD02Layout.setHorizontalGroup(
            ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoD02Layout.createSequentialGroup()
                .addGroup(ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoD02Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpCarne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ladoD02Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        ladoD02Layout.setVerticalGroup(
            ladoD02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ladoD02Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jpCarne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jpCarne2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logotipo.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("Bienvenido a tu Carné ");

        jTextArea1.setBackground(new java.awt.Color(153, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nLos mayores de 5 años podrán ver su historial de \nvacunación del 2022 en adelante y los menores de 5 años \ndesde el 2019 en adelante. \nSi tu vacunación no se encuentra registrada puedes mostrar tu carné físico.");
        jTextArea1.setFocusable(false);
        jsText1.setViewportView(jTextArea1);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Elige que Carné de Vacunación quieres mostrar.");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Haz clic en cada uno para más detalle.");

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\nSi tienes alguna observación sobre la información del Carné\nVirtual acude al establecimiento de salud donde se realizó la\nvacunación para la evaluación del caso.");
        jsText2.setViewportView(jTextArea2);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("de Vacunación");

        javax.swing.GroupLayout ladoI02Layout = new javax.swing.GroupLayout(ladoI02);
        ladoI02.setLayout(ladoI02Layout);
        ladoI02Layout.setHorizontalGroup(
            ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI02Layout.createSequentialGroup()
                .addGroup(ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ladoI02Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jsText2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jsText1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ladoI02Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel20)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        ladoI02Layout.setVerticalGroup(
            ladoI02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ladoI02Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jsText1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jsText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        btnCerrar.setText("<- Cerar Sesion");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        jpCarnet.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setBackground(new java.awt.Color(255, 255, 0));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/QREE (1) (1).png"))); // NOI18N
        jLabel24.setOpaque(true);

        lblNombre.setText("Nombre");

        lblDni.setText("DNI:");

        lblEdad.setText("Edad");

        jSeparator1.setForeground(new java.awt.Color(51, 255, 0));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 255));
        jLabel27.setText("VACUNACIÓN COVID-19");

        lblNumeroDosis.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNumeroDosis.setForeground(new java.awt.Color(51, 51, 255));
        lblNumeroDosis.setText("N° DE DOSIS");

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Dosis");

        Check2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check2.setOpaque(true);

        Check1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check1.setOpaque(true);

        Check4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check4.setOpaque(true);

        Check3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51), 5, true));
        Check3.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel30)
                .addGap(45, 45, 45)
                .addComponent(Check1)
                .addGap(18, 18, 18)
                .addComponent(Check2)
                .addGap(18, 18, 18)
                .addComponent(Check3)
                .addGap(18, 18, 18)
                .addComponent(Check4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Check4)
                    .addComponent(Check2)
                    .addComponent(Check1)
                    .addComponent(Check3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCarnetLayout = new javax.swing.GroupLayout(jpCarnet);
        jpCarnet.setLayout(jpCarnetLayout);
        jpCarnetLayout.setHorizontalGroup(
            jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCarnetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCarnetLayout.createSequentialGroup()
                        .addComponent(lblDni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEdad))
                    .addGroup(jpCarnetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addGroup(jpCarnetLayout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addGap(126, 126, 126)))))
                .addGap(70, 70, 70))
            .addGroup(jpCarnetLayout.createSequentialGroup()
                .addGroup(jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCarnetLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCarnetLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(lblNumeroDosis))
                    .addGroup(jpCarnetLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel27)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jpCarnetLayout.setVerticalGroup(
            jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCarnetLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(47, 47, 47)
                .addComponent(lblNombre)
                .addGap(43, 43, 43)
                .addGroup(jpCarnetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroDosis)
                .addGap(27, 27, 27)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout CarnetCovidLayout = new javax.swing.GroupLayout(CarnetCovid);
        CarnetCovid.setLayout(CarnetCovidLayout);
        CarnetCovidLayout.setHorizontalGroup(
            CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarnetCovidLayout.createSequentialGroup()
                .addGroup(CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CarnetCovidLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnCerrar))
                    .addGroup(CarnetCovidLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jpCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        CarnetCovidLayout.setVerticalGroup(
            CarnetCovidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarnetCovidLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/descarga.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 50));

        content02.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout content02Layout = new javax.swing.GroupLayout(content02);
        content02.setLayout(content02Layout);
        content02Layout.setHorizontalGroup(
            content02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        content02Layout.setVerticalGroup(
            content02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(content02, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 540, 810));

        content01.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout content01Layout = new javax.swing.GroupLayout(content01);
        content01.setLayout(content01Layout);
        content01Layout.setHorizontalGroup(
            content01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        content01Layout.setVerticalGroup(
            content01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        getContentPane().add(content01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2MouseClicked
    int numeroDocumento;
    private void btnContinuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnContinuarMouseClicked
        Logica logica = new Logica();
        camposVacios();
        numeroDocumento = Integer.parseInt(txtDocumento.getText());
        if (!logica.validarExistencia(numeroDocumento, txtNacimiento.getText(), txtEmision.getText())) {
            Verificacion = false;
        }

        // TODO add your handling code here:
        if (Verificacion) {
            numeroDocumento = Integer.parseInt(txtDocumento.getText());
            ladoD02.setSize(540, 810);
            ladoD02.setLocation(0, 0);
            content02.removeAll();
            content02.add(ladoD02, BorderLayout.CENTER);
            content02.revalidate();
            content02.repaint();
            ladoI02.setSize(540, 810);
            ladoI02.setLocation(0, 0);
            content01.removeAll();
            content01.add(ladoI02, BorderLayout.CENTER);
            content01.revalidate();
            content01.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "INGRESE LOS DATOS CORRECTOS DEL DOCUMENTO");
        }

    }//GEN-LAST:event_btnContinuarMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        CarnetCovid.setSize(540, 810);
        CarnetCovid.setLocation(0, 0);
        content01.removeAll();
        content01.add(CarnetCovid, BorderLayout.CENTER);
        content01.revalidate();
        content01.repaint();
        obtenerDatos();
    }//GEN-LAST:event_jButton4MouseClicked

    private void cbTipoDocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoDocumentoItemStateChanged
        // TODO add your handling code here:
        switch (cbTipoDocumento.getSelectedIndex()) {
            case 0 -> {
                lblEmision.setVisible(true);
                txtEmision.setVisible(true);
            }
            case 1, 2, 3, 4, 5 -> {
                lblEmision.setVisible(false);
                txtEmision.setVisible(false);
            }
            default ->
                throw new AssertionError();
        }
    }//GEN-LAST:event_cbTipoDocumentoItemStateChanged

    private void txtNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '/') {
            evt.consume(); // Ignora el evento si no es un número o '/'
        }
        if (txtNacimiento.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNacimientoKeyTyped

    private void txtNacimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacimientoKeyReleased
        // TODO add your handling code here:
        if ((txtNacimiento.getText().length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) || (txtNacimiento.getText().length() == 5 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            txtNacimiento.setText(txtNacimiento.getText() + "/");
        }
        if (esFechaValida(txtNacimiento.getText())) {
            txtNacimiento.setForeground(Color.black);
        } else {
            txtNacimiento.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtNacimientoKeyReleased

    private void txtEmisionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmisionKeyReleased
        // TODO add your handling code here:
        if ((txtEmision.getText().length() == 2 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) || (txtEmision.getText().length() == 5 && evt.getKeyCode() != KeyEvent.VK_BACK_SPACE)) {
            txtEmision.setText(txtEmision.getText() + "/");
        }
        if (esFechaValida(txtEmision.getText())) {
            txtEmision.setForeground(Color.black);
        } else {
            txtEmision.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtEmisionKeyReleased

    private void txtEmisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmisionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != '/') {
            evt.consume(); // Ignora el evento si no es un número o '/'
        }
        if (txtEmision.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEmisionKeyTyped

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtDocumento.getText().length() >= 8) {
            evt.consume(); // Ignorar la tecla si no es un dígito numérico o se alcanzó la longitud máxima
        }
        if (txtDocumento.getText().length() == 07) {
            Verificacion = true;
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void cbTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoDocumentoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        // Crear una instancia del formulario Vacunacion
        Minsa formularioVacunacion = new Minsa();

        // Hacer visible el formulario Vacunacion
        formularioVacunacion.setVisible(true);

        // Cerrar el formulario actual
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private boolean esFechaValida(String fecha) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        sdf.setLenient(false); // Hacer que el análisis de fecha sea estricto

        try {
            Date date = sdf.parse(fecha);
            Verificacion = true;
            return true; // La cadena es una fecha válida
        } catch (ParseException e) {
            Verificacion = false;
            return false; // La cadena no es una fecha válida
        }
    }

    private void camposVacios() {

        if (txtDocumento.getText().isEmpty() || txtNacimiento.getText().isEmpty()) {
            Verificacion = false;
        }
        if (cbTipoDocumento.getSelectedIndex() == 0) {
            if (txtEmision.getText().isEmpty()) {
                Verificacion = false;
            }
        }
    }

    private void obtenerDatos() {
        Logica logica = new Logica();
        lblNombre.setText(logica.obtenerNombre(numeroDocumento));
        lblDni.setText("DNI: " + numeroDocumento);
        lblEdad.setText("Edad: " + logica.obtenerEdad(numeroDocumento));
        switch (logica.obtenerNumeroDosis(numeroDocumento)) {
            case 0 ->
                lblNumeroDosis.setText("NINGUNA DOSIS");
            case 1 -> {
                lblNumeroDosis.setText("CON PRIMERA DOSIS");
                Check1.setSelected(true);
            }
            case 2 -> {
                lblNumeroDosis.setText("CON SEGUNDA DOSIS");
                Check1.setSelected(true);
                Check2.setSelected(true);
            }
            case 3 -> {
                lblNumeroDosis.setText("CON TERCERA DOSIS");
                Check1.setSelected(true);
                Check2.setSelected(true);
                Check3.setSelected(true);
            }
            case 4 -> {
                lblNumeroDosis.setText("CON CUARTA DOSIS");
                Check1.setSelected(true);
                Check2.setSelected(true);
                Check3.setSelected(true);
                Check4.setSelected(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Minsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Minsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Minsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Minsa().setVisible(true);
            }
        });
    }

    public void cambiarPanelIzquierdo(JPanel panel) {

        panel.setSize(540, 810);
        panel.setLocation(0, 0);
        content02.removeAll();
        content02.add(panel, BorderLayout.CENTER);
        content02.revalidate();
        content02.repaint();
    }

    public void cambiarPanelDerecho(javax.swing.JPanel panel) {

        panel.setSize(540, 810);
        panel.setLocation(0, 0);
        content01.removeAll();
        content01.add(panel, BorderLayout.CENTER);
        content01.revalidate();
        content01.repaint();
        panel.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CarnetCovid;
    private javax.swing.JCheckBox Check1;
    private javax.swing.JCheckBox Check2;
    private javax.swing.JCheckBox Check3;
    private javax.swing.JCheckBox Check4;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JComboBox<String> cbTipoDocumento;
    private javax.swing.JPanel content01;
    private javax.swing.JPanel content02;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel jpCarne1;
    private javax.swing.JPanel jpCarne2;
    private javax.swing.JPanel jpCarnet;
    private javax.swing.JPanel jpQr;
    private javax.swing.JPanel jpText;
    private javax.swing.JScrollPane jsText1;
    private javax.swing.JScrollPane jsText2;
    private javax.swing.JPanel ladoD01;
    private javax.swing.JPanel ladoD02;
    private javax.swing.JPanel ladoI01;
    private javax.swing.JPanel ladoI02;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmision;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumeroDosis;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtEmision;
    private javax.swing.JTextField txtNacimiento;
    // End of variables declaration//GEN-END:variables
}
